apiVersion: v2
name: nodejs-hello
description: A Helm chart for PPRO Nodejs Application
type: application
version: 0.1.0
appVersion: 1.0.0
sources:
- https://github.com/Shivox/nodejs-hello
dependencies:
- name: mysql
  version: "1.6.6"
  repository: "https://kubernetes-charts.storage.googleapis.com/"
